grafana.ini:
  allow_embedding: true
  auth.anonymous:
    enabled: true
service:
  port: 9000
  targetPort: 3000
adminUser: admin
adminPassword: admin
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-ui.monitoring.svc:9090
        editable: true
        jsonData:
          httpMethod: GET
          timeout: 120
          prometheusType: Prometheus
          prometheusVersion: ">2.40"
dashboards:
  default:
    connected-clients:
      json: |
        {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": {
                "type": "grafana",
                "uid": "-- Grafana --"
              },
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "target": {
                "limit": 100,
                "matchAny": false,
                "tags": [],
                "type": "dashboard"
              },
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "fiscalYearStartMonth": 0,
        "graphTooltip": 0,
        "id": 2,
        "links": [],
        "liveNow": false,
        "panels": [
          {
            "datasource": {
              "type": "prometheus",
              "uid": "PBFA97CFB590B2093"
            },
            "description": "Shows the total number of connected clients per room.",
            "fieldConfig": {
              "defaults": {
                "color": {
                  "mode": "palette-classic"
                },
                "custom": {
                  "axisCenteredZero": false,
                  "axisColorMode": "text",
                  "axisLabel": "",
                  "axisPlacement": "auto",
                  "barAlignment": 0,
                  "drawStyle": "bars",
                  "fillOpacity": 0,
                  "gradientMode": "none",
                  "hideFrom": {
                    "legend": false,
                    "tooltip": false,
                    "viz": false
                  },
                  "lineInterpolation": "linear",
                  "lineStyle": {
                    "fill": "solid"
                  },
                  "lineWidth": 1,
                  "pointSize": 5,
                  "scaleDistribution": {
                    "type": "linear"
                  },
                  "showPoints": "auto",
                  "spanNulls": false,
                  "stacking": {
                    "group": "A",
                    "mode": "none"
                  },
                  "thresholdsStyle": {
                    "mode": "off"
                  }
                },
                "mappings": [],
                "thresholds": {
                  "mode": "absolute",
                  "steps": [
                    {
                      "color": "green",
                      "value": null
                    },
                    {
                      "color": "red",
                      "value": 80
                    }
                  ]
                }
              },
              "overrides": [
                {
                  "__systemRef": "hideSeriesFrom",
                  "matcher": {
                    "id": "byNames",
                    "options": {
                      "mode": "exclude",
                      "names": ["test-3"],
                      "prefix": "All except:",
                      "readOnly": true
                    }
                  },
                  "properties": [
                    {
                      "id": "custom.hideFrom",
                      "value": {
                        "legend": false,
                        "tooltip": false,
                        "viz": true
                      }
                    }
                  ]
                }
              ]
            },
            "gridPos": {
              "h": 9,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "id": 2,
            "options": {
              "legend": {
                "calcs": [],
                "displayMode": "list",
                "placement": "bottom",
                "showLegend": true
              },
              "tooltip": {
                "mode": "multi",
                "sort": "none"
              }
            },
            "targets": [
              {
                "datasource": {
                  "type": "prometheus",
                  "uid": "PBFA97CFB590B2093"
                },
                "editorMode": "code",
                "expr": "number_of_connected_client",
                "instant": false,
                "legendFormat": "{{roomId}}",
                "range": true,
                "refId": "A"
              }
            ],
            "title": "Connected Clients",
            "type": "timeseries"
          }
        ],
        "refresh": "",
        "revision": 1,
        "schemaVersion": 38,
        "style": "dark",
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-6h",
          "to": "now"
        },
        "timepicker": {},
        "timezone": "",
        "title": "Connected Clients",
        "uid": "zgPi6ZyVk",
        "version": 5,
        "weekStart": ""
        }
